# Generated by Django 3.2.7 on 2023-10-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('athlete', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='register.athlete')),
                ('sponsors', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_donations', to='register.sponsor')),
            ],
            options={
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
