# Generated by Django 3.2.7 on 2023-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='regular_user', max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
