# Generated by Django 3.2.7 on 2023-10-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20231004_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
