# Generated by Django 3.2.7 on 2023-10-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20231005_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
